{ types, assertions, ... }:
{
  inputs = {
    mkWrapper.from = { parent }: parent.mkWrapper;
    nixpkgs.from = { parent }: parent.nixpkgs;
  };

  options = {
    settings = {
      type = types.attrs;
      description = ''
        Settings to be injected into the wrapped package's `kitty.conf`.

        See the kitty [documentation](https://sw.kovidgoyal.net/kitty/conf.html).

        Disjoint with the `configFile` option.
      '';
    };
    configFile = {
      type = types.pathLike;
      description = ''
        `kitty.conf` file to be injected into the wrapped package.

        See the kitty [documentation](https://sw.kovidgoyal.net/kitty/conf.html).

        Disjoint with the `settings` option.
      '';
    };

    theme = {
      type = types.string;
      description = ''
        Theme name from `pkgs.kitty-themes` to be used.

        Each of the files in [this folder](https://github.com/kovidgoyal/kitty-themes/tree/master/themes) constitute a valid theme.
      '';
      example = "Catppuccin-Mocha";
    };
    themeFile = {
      type = types.pathLike;
      description = ''
        Path containing a Kitty theme to be used.
      '';
    };

    portalSettings = {
      type = types.attrs;
      description = ''
        XDG desktop portal settings to be injected into the wrapped package's `kitty.conf`.

        See the kitty [documentation](https://sw.kovidgoyal.net/kitty/kittens/desktop-ui/#appearance).

        Disjoint with the `portalConfigFile` option.
      '';
    };
    portalConfigFile = {
      type = types.pathLike;
      description = ''
        `desktop-ui-portal.conf` file to be injected into the wrapped package.

        See the kitty [documentation](https://sw.kovidgoyal.net/kitty/kittens/desktop-ui/#appearance).

        Disjoint with the `portalSettings` option.
      '';
    };

    package = {
      type = types.derivation;
      defaultFunc = { inputs }: inputs.nixpkgs.pkgs.kitty;
      description = "The kitty package to be wrapped.";
    };
  };

  assertions = [
    (assertions.disjoint "settings" "configFile")
    (assertions.disjoint "theme" "themeFile")
    (assertions.disjoint "portalSettings" "portalConfigFile")
  ];

  mutations."/fish".interactiveShellInit =
    { options }:
    # fish
    ''
      # We can't use the `shell_integration` output of our wrapper, since wrappers
      # don't preserve attributes like this
      source "${options.package.shell_integration}/fish/vendor_conf.d/kitty-shell-integration.fish"
      set --prepend fish_complete_path "${options.package.shell_integration}/fish/vendor_completions.d"
    '';

  impl =
    { options, inputs }:
    let
      inherit (builtins) concatStringsSep;
      inherit (inputs.nixpkgs.pkgs) formats writeText;
      inherit (inputs.nixpkgs.lib) generators optionalString;
      # Slightly modified from hjr source - the one defined in hm does a lot of
      # extra nonsense, that im hoping isnt necessary
      generator = formats.keyValue {
        listToValue = list: concatStringsSep " " (map toString list);
        mkKeyValue = generators.mkKeyValueDefault {
          mkValueString =
            value:
            if value == true then
              "yes"
            else if value == false then
              "no"
            else
              generators.mkValueStringDefault {} value;
        } " ";
      };
    in
    inputs.mkWrapper {
      inherit (options) package;
      binaryPaths = [
        "$out/bin/kitty"
        "$out/bin/kitten"
      ];
      symlinks = {
        "$out/kitty/kitty.conf" = writeText "kitty.conf" ''
          # Auto-generated by adios-wrappers
          ${
            if options ? configFile then
              "include ${options.configFile}"
            else if options ? settings then
              "include ${generator.generate "kitty" options.settings}"
            else
              ""
          }
          ${optionalString (options ? themeFile || options ? theme) "include current-theme.conf"}
        '';

        "$out/kitty/current-theme.conf" =
          if options ? themeFile then
            options.themeFile
          else if options ? theme then
            "${inputs.nixpkgs.pkgs.kitty-themes}/share/kitty-themes/themes/${options.theme}.conf"
          else
            null;

        "$out/kitty/desktop-ui-portal.conf" =
          if options ? portalConfigFile then
            options.portalConfigFile
          else if options ? portalSettings then
            writeText "desktop-ui-portal.conf" ''
              # Auto-generated by adios-wrappers
              include ${generator.generate "desktop-ui-portal" options.portalSettings}
            ''
          else
            null;
      };
      environment = {
        KITTY_CONFIG_DIRECTORY = "$out/kitty";
      };
    };

  meta = {
    maintainers = [ "llakala" ];
  };
}
